### ISSUE TITLE
pyErrorPred.predict error

### ISSUE THREAD

**Issue by jlspzw** [hiranumn/DeepAccNet#1]
It seems the pyErrorPred.predict not correct

the predict function in DeepAccNet.py

        result = pyErrorPred.predict(samples,
                                        modelpath,
                                        args.output,
                                        num_blocks=5,
                                        num_filters=128,
                                        verbose=args.verbose,
                                        ensemble=args.ensemble,
                                       csv = args.csv)

while the function in predict.py looks like

def predict(samples, modelpath, outfolder, num_blocks=5, num_filters=128, ensemble=False, verbose=False):
    
    n_models = 5 if ensemble else 2
    for i in range(1, n_models):
        modelname = modelpath+"_rep"+str(i)
        if verbose: print("Loading", modelname)
        model = Model(obt_size = 70,
                      tbt_size = 33,
                      prot_size = None,
                      num_chunks = num_blocks,
                      channel = num_filters,
                      optimizer = "adam",
                      loss_weight = [1.0, 0.25, 10.0],
                      name = modelname,
                      label_smoothing = False,
                      no_last_dilation = True,
                      partial_instance_norm = True,
                      bert = False)
        model.load()
            
        for j in range(len(samples)):
            if verbose: print("Predicting for", samples[j], "(network rep"+str(i)+")") 
            tmp = join(outfolder, samples[j]+".features.npz")
            batch = getData(tmp)
            lddt, estogram, mask = model.predict(batch)
            if not ensemble:
                np.savez_compressed(join(outfolder, samples[j]+".npz"),
                                    lddt = lddt,
                                    estogram = estogram,
                                    mask = mask)
            else:
                np.savez_compressed(join(outfolder, samples[j]+".rep"+str(i)+".npz"),
                                    lddt = lddt,
                                    estogram = estogram,
                                    mask = mask)

No csv option and no return value.

Please double-check if the code version is correctly uploaded.
Best

**Comment by hiranumn** [comment]
Thanks for pointing out. Should be good now.
