### ISSUE TITLE
Source code for refinement

### ISSUE THREAD

**Issue by xiaogenz00** [hiranumn/DeepAccNet#2]
It's a very interesting work. The code here can only predict the accuracy. I would appreciate it if you could provide the source code for refinement.

**Comment by hiranumn** [comment]
We are still preparing for the refinement code to go public. It would still take a bit of time.

**Comment by hahnbeom** [comment]
> It's a very interesting work. The code here can only predict the accuracy. I would appreciate it if you could provide the source code for refinement.

Hello,

Thank you for your request! Those scripts will be added in this github as well, although may take a bit of time for cleanup. If you can leave your e-mail address here, I will let you know when it's ready.

**Comment by xiaogenz00** [comment]
> > It's a very interesting work. The code here can only predict the accuracy. I would appreciate it if you could provide the source code for refinement.
> 
> Hello,
> 
> Thank you for your request! Those scripts will be added in this github as well, although may take a bit of time for cleanup. If you can leave your e-mail address here, I will let you know when it's ready.

Thanks! My e-mail address is xiaogenz@umich.edu.

**Comment by hiranumn** [comment]
Hi,

The code is upload to the "modeling" folder. Let me know if you have questions.
