### ISSUE TITLE
Error: "While processing output/model.features.npz:need at least one array to stack" results in no npz file.

### ISSUE THREAD

**Issue by daipayans** [hiranumn/DeepAccNet#2]
Hi, 
On running the script `DeepAccNet.py`, I get this error for a specific model.pdb. Please advise on how to troubleshoot this issue. Note, I have tested on other model PDB input files and it appears to work fine. Any help is sincerely appreciaterd. 
With my best regards,
Daipayan

**Comment by hiranumn** [comment]
Hi Daipayan,

Thank you for your inquiry. Would it be possible to share the problematic model.pdb? 
If that is not possible, may be could you share the error meassage?

Best,
Nao
