### ISSUE TITLE
Error in cst file generation

### ISSUE THREAD

**Issue by YaoYinYing** [hiranumn/DeepAccNet#3]
Hi Hiranumn, 
Nice project!
when i tried working with estogram2cst.py by using the samples/tag0137.relaxed.al.pdb together with outputs/tag0137.relaxed.al.npz (both were copied to a new dir and renamed), theres an error related to Pref and Pavrg . the command was automatically generated by MainDiversification.py.

cst files were empty. Would u please help me with that? THX!
 the error msg is attached.
[errormsg.txt](https://github.com/hiranumn/DeepAccNet/files/6181859/errormsg.txt)

i simply printed out the lengthes of Pref and Pavrg - they are not equal to each other.

update#1
the readme of modeling script notes that the version of PyRosetta is 3 but the codes use some expressions like 'import pyrosetta' or 'from pyrosetta import *', both of which are only available with PyRosetta-4. 

so i just wonder if there may be any mistakes inside ur doc or i just confused by some magical things.  : -)

**Comment by davidesala** [comment]
Got the same problem, still unsolved. If anyone can help please get in touch.

**Comment by hahnbeom** [comment]
Hello everyone, sorry for my late fix. This happened due to the dimension change in DeepAccNet npz file. Latest fix I just pushed should make it compatible.
